# Generated by Django 6.0.5 on 2026-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_auth_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code_id',
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
