# Generated by Django 6.0.5 on 2026-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('school', 'School Level (1-10)'), ('college', 'College Level (XI-XII)'), ('bachelor', 'Bachelor Level')], default='school', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester for Bachelor level (1-8)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(help_text='Class/Division (e.g., 1, 5, 10, XI, XII, etc.)', max_length=20),
        ),
    ]
