# Generated by Django 4.2.29 on 2026-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_level_alter_student_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('code', models.CharField(choices=[('school', 'School Level (1-10)'), ('college', 'College Level (XI-XII)'), ('bachelor', 'Bachelor Level')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.educationlevel'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.semester'),
        ),
    ]
