# Generated by Django 4.2.29 on 2026-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_educationlevel_semester_teacher_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_marks',
            field=models.PositiveIntegerField(default=100, help_text='Default total marks for this subject (used when adding marks)'),
        ),
    ]
