# Generated by Django 4.2.29 on 2026-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates if this teacher has admin privileges with full system access'),
        ),
    ]
