# Generated by Django 4.2.29 on 2026-05-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.coursematerial'),
        ),
    ]
