# Generated by Django 6.0.5 on 2026-05-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cleanup_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2025-2026', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard, Division, GPA 4.0', max_length=50, unique=True)),
                ('pass_mark_percent', models.FloatField(default=40.0, help_text='Minimum % to pass')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['student__name', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Date of admission', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, help_text='e.g. A+, B-, O+', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, help_text='e.g. Red, Blue, Green, Yellow House', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Has the student been promoted to next class'),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship',
            field=models.BooleanField(default=False, help_text='Is the student on scholarship'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False, help_text='Is this a practical/internal subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.PositiveIntegerField(default=40, help_text='Minimum marks to pass'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_marks',
            field=models.PositiveIntegerField(default=100, help_text='Default total marks for this subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates if this teacher has admin privileges'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.academicyear'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All (Students, Teachers, Admin)'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('class', 'Specific Class'), ('parents', 'Parents')], default='all', max_length=20)),
                ('target_class', models.CharField(blank=True, help_text='If audience=class, specify class (e.g., 10, XI)', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this date the announcement auto-hides', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.teacher')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_class', models.CharField(help_text='Target class (e.g., 10, XI, S1)', max_length=20)),
                ('target_section', models.CharField(default='', help_text='Target section', max_length=5)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('total_marks', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject')),
                ('target_students', models.ManyToManyField(blank=True, help_text='Leave empty for whole class', related_name='assigned_assignments', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homeworks', to='core.teacher')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='core.teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.department'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Mid Term 2025', max_length=200)),
                ('exam_type', models.CharField(choices=[('unit', 'Unit Test'), ('mid', 'Mid Term'), ('terminal', 'Terminal Exam'), ('final', 'Final Exam'), ('prelim', 'Preliminary'), ('practical', 'Practical / Viva')], default='terminal', max_length=20)),
                ('target_class', models.CharField(max_length=20)),
                ('target_section', models.CharField(default='', max_length=5)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('venue', models.CharField(blank=True, help_text='Room / Hall / Online', max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exams', to='core.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.subject')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('exam', 'Exam Fee'), ('library', 'Library Fee'), ('transport', 'Transport Fee'), ('laboratory', 'Laboratory Fee'), ('sports', 'Sports Fee'), ('misc', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=15)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to='core.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.student')),
            ],
            options={
                'ordering': ['-due_date', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('relation', models.CharField(default='Father', help_text='Relationship to student', max_length=50)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info', to='core.student')),
            ],
            options={
                'ordering': ['student__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_class', models.CharField(max_length=20)),
                ('previous_section', models.CharField(blank=True, max_length=5)),
                ('promoted_to_class', models.CharField(max_length=20)),
                ('promoted_to_section', models.CharField(blank=True, max_length=5)),
                ('total_marks_obtained', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Student Academic Histories',
                'ordering': ['-academic_year__start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('add_marks', 'Added Marks'), ('edit_marks', 'Edited Marks'), ('delete_marks', 'Deleted Marks'), ('add_student', 'Added Student'), ('edit_student', 'Edited Student'), ('delete_student', 'Deleted Student'), ('add_teacher', 'Added Teacher'), ('add_material', 'Uploaded Course Material'), ('delete_material', 'Deleted Course Material'), ('publish_result', 'Published Results'), ('add_assignment', 'Created Assignment'), ('add_attendance', 'Recorded Attendance'), ('add_exam', 'Created Exam'), ('add_fee', 'Created Fee Record'), ('add_announcement', 'Published Announcement'), ('bulk_upload', 'Bulk Marks Upload'), ('promote_student', 'Promoted Student'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='core_activi_user_id_d4f94a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, help_text='Written response')),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late'), ('missing', 'Missing')], default='submitted', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='core.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='core.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'), models.Index(fields=['date', 'status'], name='core_attend_date_7783ad_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_performance', models.PositiveIntegerField(default=80, help_text='Subject knowledge rating (1-100)')),
                ('punctuality', models.PositiveIntegerField(default=80, help_text='Punctuality rating (1-100)')),
                ('communication', models.PositiveIntegerField(default=80, help_text='Communication skills (1-100)')),
                ('student_satisfaction', models.PositiveIntegerField(default=80, help_text='Student satisfaction (1-100)')),
                ('overall_score', models.FloatField(default=0.0, help_text='Auto-calculated average')),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'evaluator', 'academic_year')},
            },
        ),
    ]
